# Numpy 
### wird benutzt um numerische Daten auszulesen

erstmal ohne numpy:

In [2]:
umfrage_person_1 = [2, 1, 1, 4, 3, 5, 1, 3, 2]
umfrage_person_2 = [1, 5, 3, 4, 2, 1, 3, 5, 1]

# datentyp liste:
# ziel delta zwischen den einträgen in der Liste

umfrage_delta = []
for i in range(len(umfrage_person_1)):
    delta = abs(umfrage_person_1[i] - umfrage_person_2[i])
    umfrage_delta.append(delta)
    
print(umfrage_delta)


[1, 4, 2, 0, 1, 4, 2, 2, 1]


vergleichsbeispiel mit numpy:

In [11]:
import numpy as np

umfrage_person_1_np = np.array([2, 1, 1, 4, 3, 5, 1, 3, 2])
umfrage_person_2_np = np.array([1, 5, 3, 4, 2, 1, 3, 5, 1])

umfrage_delta_np = umfrage_person_1_np - umfrage_person_2_np

print(abs(umfrage_delta_np))



[1 4 2 0 1 4 2 2 1]


mit numpy kann man easy mit arrays rechnen, ohne immer über die verschiedenen teile in einer liste zu iterrieren

In [15]:
a = np.array([3, 6.4, 3, 6.3, 4.6, 2, 0.002])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# ein array kann ints, floats und listen beinhalten!
print(a)
print(b)
print()
print(a.dtype, " -> datentyp") # datentyp
print(b.ndim, " -> wie viele dimensionen") # wie viele dimensionen 
print(b.size, " -> wie viele einträge") # wie viele einträge
print(b.shape, " -> anordnung der einträge") # anordnung der einträge


[3.0e+00 6.4e+00 3.0e+00 6.3e+00 4.6e+00 2.0e+00 2.0e-03]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

float64  -> datentyp
2  -> wie viele dimensionen
9  -> wie viele einträge
(3, 3)  -> anordnung der einträge


anders als eine liste (wo alles gemische rein kann), muss ein numpy array immer den gleichen datentyp beinhalten.
wenn es ein float in einer liste von ints gibt werden alle ints zu float konvertiert.

> [1, 2, 3.5]  ->  [1. 2. 3.5]



In [19]:
a = np.array([3, 6.4, 3, 6.3, 4.6, 2, 0.002])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b[1])
print("gibt das erste 'element' des arrays aus.\nhier: die erste zeile")
print()
print(b[0][0])
print("erstes element der ersten zeile")

[4 5 6]
gibt das erste 'element' des arrays aus.
hier: die erste zeile

1
erstes element der ersten zeile


man kann ein listenelement über zwei varianten aufrufen:
> b[i][j]
> b[i, j]

In [22]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(matrix[:, :], '\n')
print(matrix[1:, 1:], '\n')
print(matrix[:1, :1], '\n')
print(matrix[:2, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[5 6]
 [8 9]] 

[[1]] 

[[1 2]
 [4 5]]


man kann funky stuff mit arrays und numpy machen!

In [27]:
print(matrix < 5)

mask = matrix < 5 # es wird eine maske erstellt
print(matrix[mask]) # die maske wird angewendet, returnt dann nur die werte die in der maske true sind! 

# hier verliert man die info wo die einträge im array sind, deshalb:

print(np.where(mask)) # returns positionen für True (array1 entspricht x-Koordinate, array2 entspricht y-Koordinate)

print()

mask_2 = (matrix >= 2) & (matrix < 7)
mask_3 = (matrix < 2) | (matrix > 7)
print(mask_2)
print()
print(mask_3)


[[ True  True  True]
 [ True False False]
 [False False False]]
[1 2 3 4]
(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

[[False  True  True]
 [ True  True  True]
 [False False False]]

[[ True False False]
 [False False False]
 [False  True  True]]


## Rechnen mit np.arrays

rechnen mit zwei arrays geht nur wenn beide/alle arrays die selbe dimension haben

In [33]:
numbers = np.array([4, 5, 1, 3, 6, 3, 5])
other_numbers = np.array([2.2, 6, 4.8, 3, 6.1, 2, 1.6])

print(numbers * 5)
print(numbers/100)
print(numbers - 7)
print(numbers - other_numbers)

[20 25  5 15 30 15 25]
[0.04 0.05 0.01 0.03 0.06 0.03 0.05]
[-3 -2 -6 -4 -1 -4 -2]
[ 1.8 -1.  -3.8  0.  -0.1  1.   3.4]


weitere operatoren:

> data.max()

> data.min()

> data.sum()


erstelle ein np array, es füllt ein array mit nullen

In [42]:
data_zeros = np.zeros((7, 9))
data_ones = np.ones((7, 9))

# print(data_zeros)
# print(data_ones)
# print(data_zeros.shape)

# mittelwert aus 10000 beliebigen zahlen
data = np.random.random((100, 100))
print(data.mean())


0.5051695734047644


In [46]:
data = np.random.random((3, 3, 3, 3, 3, 3))
print(data.shape)
print(data.mean())
print(data.size)

(3, 3, 3, 3, 3, 3)
0.5064017280227003
729


In [47]:
data = np.arange(0, 10, 0.5) # start_value, end_value, step_size
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
data = np.linspace(-5, 10, 10) # start and end values are start and endpoints in the array, with exact equal steps between them
print(data)

[-5.         -3.33333333 -1.66666667  0.          1.66666667  3.33333333
  5.          6.66666667  8.33333333 10.        ]


# manipulating datapoint in an array using a mask

In [50]:
matrix = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

mask = matrix >= 5

matrix[mask] = 100
print(matrix)

[[  1   2   3]
 [  4 100 100]
 [100 100 100]]


In [53]:
data = np.arange(1, 10, 1) # start_value, end_value, step_size
print(data)
print(data.size)
print(data.shape)

data_2 = data.reshape(3, 3)
print(data_2)
print(data_2.shape)


[1 2 3 4 5 6 7 8 9]
9
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
