In [18]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn import datasets, metrics, svm
from sklearn.model_selection import train_test_split

In [8]:
data_dir = "/home/arabanus/Desktop/intlsys_logs/"
m_1 = "logfile_deo_dose_53mm.txt"
m_2 = "logfile_dose_zweite_messung.txt"
m_3 = "logfile_dose_dritte_messung.txt"

df_dose1 = pd.read_csv(data_dir + m_1, header=None)
df_dose2 = pd.read_csv(data_dir + m_2, header=None)
df_dose3 = pd.read_csv(data_dir + m_3, header=None)

# print(df_dose1.T.shape[1])

610


In [27]:
def reshape_measurement(df, num_rot=10):
    """
    input pd df w/ shape: (1, n)
    output: pd df w/ shape (num_rot, n/num_rot)
    """
    all_entries = df.shape[1]
    reshaped_df = df.values.reshape(num_rot, all_entries//num_rot)
    return reshaped_df

combined_df = np.concatenate([reshape_measurement(df_dose1.T),
                              reshape_measurement(df_dose2.T),
                              reshape_measurement(df_dose3.T)],
                              axis=0)

print(combined_df)
print(combined_df.shape)

[[5.051546 5.051546 5.051546 ... 5.034364 5.051546 5.034364]
 [5.051546 5.034364 5.034364 ... 5.051546 5.051546 5.051546]
 [5.051546 5.051546 5.051546 ... 5.051546 5.051546 5.034364]
 ...
 [5.670103 5.704467 5.704467 ... 4.725086 6.030928 6.013746]
 [5.72165  5.72165  5.704467 ... 6.030928 6.030928 5.704467]
 [5.72165  5.704467 5.687285 ... 6.030928 5.704467 5.704467]]
(30, 61)


In [ ]:
clf = svm.SVC(gamma=0.001)

X_train, X_test, y_train, y_test = train_test_split(
    combined_df, digits.target, test_size=0.5, shuffle=False
) 
# was macht .target bei scikit learn

# Learn the digits on the train subset
clf.fit(X_train, y_train)

# Predict the value of the digit on the test subset
predicted = clf.predict(X_test)